name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'harsh-music-functions'     # ← replace with your Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'                 # ← adjust if your code lives in a subfolder
  PYTHON_VERSION: '3.12'                               # ← match your runtime, e.g. 3.8, 3.9, etc.

jobs:
  build-and-deploy:
    runs-on: Linux
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # If you’d rather use Azure Service Principal auth, uncomment these lines 
      # and remove the publish-profile line below
      #- name: Login via Azure CLI
      #  uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Resolve dependencies
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}   # ← leave this if you’re using the Publish Profile
          scm-do-build-during-deployment: true
          enable-oryx-build: true
